# Generated by Django 5.0.3 on 2024-04-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIF', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorisedDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_authorisedDealer', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('NIF_bussines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NIF_bussines', to='Car_Renting.business')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('licensePlate', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('mileage', models.IntegerField(default=0)),
                ('AuthorisedDealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AuthorisedDealer', to='Car_Renting.authoriseddealer')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('correo_cliente', models.EmailField(default=None, max_length=254)),
                ('NIF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Renting.business')),
                ('car_rented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rented', to='Car_Renting.car')),
                ('id_authorisedDealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Renting.authoriseddealer')),
            ],
        ),
    ]
