# Generated by Django 5.0.3 on 2024-03-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Renting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorisedDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_authorisedDealer', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIF', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='licensePlate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('NIF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Renting.business')),
                ('id_authorisedDealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Renting.authoriseddealer')),
                ('licensePlate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Renting.car')),
            ],
        ),
    ]
