# Generated by Django 5.0.3 on 2024-04-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Renting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoriseddealer',
            name='id_authorisedDealer',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='NIF',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='licensePlate',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
